


char findTheDifference(char * s, char * t){
    char ret;
    int len_s=0,len_t=0,i=0,flag=1;
    
    while(s[i]!='\0') ++len_s,i++;
    i=0;
    while(t[i]!='\0') ++len_t,i++;
    
    if(len_s==len_t){ //
        for(i=0;i<=len_s&&flag;i++){
            flag=0;
            for(int j=0;j<=len_s;j++){
                if(s[i]==t[j]){flag=1; break;}
            }
        }
        ret=s[i-1];
    }
    
    else if(len_s>len_t){ //
        for(i=0;i<=len_s&&flag;i++){
            flag=0;
            for(int j=0;j<=len_t;j++){
                if(t[j]==NULL) continue;
                if(s[i]==t[j]){t[j]=NULL;flag=1;break;}
            }
        }
        ret=s[i-1];
    }
    
    else if(len_s<len_t){ //
        for(i=0;i<=len_t&&flag;i++){
            flag=0;
            for(int j=0;j<=len_s;j++){
                if(s[j]==NULL) continue;
                if(s[j]==t[i]){s[j]=NULL;flag=1;break;}
            }
        }
        ret=t[i-1];
    }
   
    return ret;
}

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

